name: BuildPageExperimental

on:
  push:
    branches: ["test-action"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      # https://github.com/actions/checkout
      # 拉取代码
      - name: Checkout codes
        uses: actions/checkout@v3

      # https://github.com/actions/setup-node
      # 安装 node 并缓存 pnpm
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # https://github.com/pnpm/action-setup
      # 安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # https://pnpm.io/zh/cli/install#--frozen-lockfile
      # 使用 pnpm 安装依赖
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --ignore-scripts
  
      # 构建
      - name: Build Test
        run: pnpm --filter pages build

      # 查看构建后的文件
      - name: View Files
        run: ls ./pages/dist
        